# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
